### ISSUE TITLE
Uncaught Error: Invalid Jalaali year 10111095

### ISSUE THREAD

**Issue by ghost** [jalaali/jalaali-js#11]
Hi. I Wanna Use 'toJalaali' For my project.
when I Use Below Code, Run Perfectly
` console.log(jalaali.toJalaali(2016, 4, 11));`

but When I Use Variables For my 'Year,Month,Day', I Will get Error:

`let y='2016',m='4',d='11';
console.log(jalaali.toJalaali(y, m, d));`

Now I Get this Error : 

> Uncaught Error: Invalid Jalaali year 10111095
    at jalCal (admin.js:11425)
    at d2j (admin.js:11489)
    at Object.toJalaali (admin.js:11357)
    at get_date (admin.js:14450)
    at Object.success (admin.js:37042)
    at fire (admin.js:4124)
    at Object.fireWith [as resolveWith] (admin.js:4254)
    at done (admin.js:10161)
    at XMLHttpRequest.<anonymous> (admin.js:10404)
jalCal @ admin.js:11425
d2j @ admin.js:11489
toJalaali @ admin.js:11357
get_date @ admin.js:14450
success @ admin.js:37042
fire @ admin.js:4124
fireWith @ admin.js:4254
done @ admin.js:10161
(anonymous) @ admin.js:10404
load (async)
send @ admin.js:10423
ajax @ admin.js:10062
(anonymous) @ admin.js:37024
dispatch @ admin.js:6039
elemData.handle @ admin.js:5847

**Comment by behrang** [comment]
You are passing strings to the function. Pass numbers and it should work.

I'm closing this issue. If it didn't work, reopen it.
