### ISSUE TITLE
different result .toJalaali() in server and client

### ISSUE THREAD

**Issue by masihjahangiri** [jalaali/jalaali-js#14]
in SSR must be same result in server and client.
 result of .toJalaali() is not same in server and client for example:
```javascript
const result = jalaali.toJalaali( new Date('2016-04-24 01:56:24.000'));
console.log(result); 
// server = { jy: 1395, jm: 2, jd: 4 }
// client = { jy: 1395, jm: 2, jd: 5 }
```

**Comment by behrang** [comment]
It must be because of difference in timezone of client and server. Please check your timezone on both environments, and update here. You may also print the `new Date(...)` part to console to see if the timezone of both match or not.

**Comment by alitaheri** [comment]
@masihjahangiri also note that the behavior of `new Date()` [varies drastically across environments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters). so, if possible please provide a valid ISO8601 date string i.e. `2016-04-24T01:56:24.000Z` which indicates that the timezone is UTC. or `2016-04-24T01:56:24.000+04:00` for setting the timezone. Omitting the `Z` or the offset means the time is in local timezone, which can be wrong, or can be interpreted differently across environments. so always append the `Z` or use an static offset. don't rely on local timezone.

**Comment by imanro86** [comment]
you just create date string with format "2016-04-24 01:56:24.000 GMT+0330" in new Date();
