### ISSUE TITLE
[Feature Request] Add iso-weekday method

### ISSUE THREAD

**Issue by MoKhajavi75** [jalaali/jalaali-js#17]
Hey

Thanks for your efforts! :heart: 

May I ask for an `jalaaliISOWeekday` (something like [`iso-weekday`](https://momentjs.com/docs/#/get-set/iso-weekday/)) method?

**Comment by behrang** [comment]
For `moment` related issues, you have to create it on `jalaali/moment-jalaali`.

**Comment by MoKhajavi75** [comment]
> For `moment` related issues, you have to create it on `jalaali/moment-jalaali`.
> […](#)
> On Esfand 12, 1398 AP, 10:12 PM +0330, Mohamad Khajavi ***@***.***>, wrote: Hey Thanks for your efforts!  May I ask for a iso-weekday method? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Well, I didn't want to install moment for this :smile: 
I handle it in a different way. Converted to Gregorian and then use `getDays`

Anyway, thanks!
