### ISSUE TITLE
Gregorian to Jalali

### ISSUE THREAD

**Issue by dlbaran** [jalaali/jalaali-js#21]
Hi,
I need to display the date stored in the Gregorian database in Jalali. How can I do this using your library?

**Comment by kayvaninvemo** [comment]
Is the code you provided JavaScript?

**Comment by dlbaran** [comment]
> Is the code you provided JavaScript?

No, This is a PHP code.

**Comment by behrang** [comment]
You should open the issue on the PHP version: https://github.com/jalaali/jalaali-php
