### ISSUE TITLE
`jalaaliToDateObject` is not available yet documented

### ISSUE THREAD

**Issue by mhsattarian** [jalaali/jalaali-js#28]
Newly documented method, `jalaaliToDateObject` is not available yet, neither in the NPM module nor CDN.

Also, it would come really handy if `toGregorian` method and `jalaaliToDateObject` both accepted time arguments like hours, minutes and seconds as well.

**Comment by MoKhajavi75** [comment]
I just faced it 😁 

cc @behrang

**Comment by behrang** [comment]
Ok, I've published another version to NPM. Please check, and if it was ok, close this issue.

About hour, minute, etc. this project is trying to only convert Gregorian dates, time part usually stays the same. However, you may argue that this improves experience and ease of use. In that case, propose a solution beside the current one and send a PR and I'll merge it. Just consider backwards compatibility.

**Comment by mhsattarian** [comment]
I've just tested it, and it's working fine. thanks.

**Comment by mhsattarian** [comment]
Also, about the time params, I opened a PR (#29).
