### ISSUE TITLE
issue with the 1.2.0 version published package

### ISSUE THREAD

**Issue by m-ahmadi** [jalaali/jalaali-js#30]
Hi,

It seems that the `1.2.0` version has been published with issues.

The published package does not contain the assets specified in the `package.json` `files` field,
therefore the `dist` directory has not been published.

So if I do
```shell
mkdir x
cd x
npm i jalaali-js@1.1.5
```
then there exist `x/node_modules/jalaali-js/dist`.

but when `npm i jalaali-js@1.2.0`, then no `dist` dir exists.

I'm not sure what has caused this.

But on my machine, if I do the following:
```shell
git clone git@github.com:jalaali/jalaali-js.git
cd jalaali-js
npm i
npm run prepare
```
I get no error on `npm i` and `npm run prepare` commands.

My `npm -v` is `7.19.1`.
My `node -v` is `16.6.1`

One thing to test is to see if you can run `npm run prepare` without any errors.

**Comment by behrang** [comment]
Hi,

Thanks for the report. I think something is changed in a version of npm, changing the semantics of files field.

Anyway, I've removed it and instead added an empty .npmignore file, and published 1.2.2.

**Comment by m-ahmadi** [comment]
> I think something is changed in a version of npm, changing the semantics of files field.

I suspected the same thing, but then I looked in the [npm-docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) and couldn't find any major change in its semantics.

Regarding the `.npmignore` file, currently as of `1.2.2` this file does not ignore anything, (because it's empty),
So now [everything is published](https://cdn.jsdelivr.net/npm/jalaali-js@1.2.2/) in the package including the `build` dir and the `build-umd.js` file that were previously ignored on [`1.1.5`](https://cdn.jsdelivr.net/npm/jalaali-js@1.1.5/).

If the `.npmignore`  file contains the following:
```
build
build-umd.js
```
then, it's equivalent of the following `files` field:
```
"files": [
  "*",
  "!build",
  "!build-umd.js"
]
```

So to test whether using `.npmignore` is any different than the `files`, you can add the following to the `.npmignore` file
```
build
build-umd.js
```
then, publish `1.2.3`,

then, look in [this folder](https://cdn.jsdelivr.net/npm/jalaali-js@1.2.3/),

and if there isn't a `build` dir and a `build-umd.js` file in it, but there is a `dist` folder, then everything is back to normal same as in `1.1.5`,

but if there isn't a `dist` folder, then it proves that the root issue still exist and having used `.npmignore` didn't have the desired effect.

**Comment by behrang** [comment]
I intentionally made .npmignore empty, so that it differs from .gitignore. This way, `dist` folder will be published. The `build` and `build-umd.js` files weren't important, so I let them remain in the published package. If you believe it's better to remove them from the published package, let me know and I do as you said.

**Comment by m-ahmadi** [comment]
As far as being important, no those files do not have any effect and current package at `1.2.2` is working fine.
But I was trying to keep everything as it was on previous versions.

Although one difference of assets included in the package, relates to how much bandwidth is used when the pkg is installed by npm.

So the size of  `build` dir and `build-umd.js` file is `7.36 KB`,
and this package is downloaded let's say `18,000` times a week,
so that sums up to `132.48 MB` of bandwidth per peek.

But as long as we are discussing this aspect, there other files in the package that seem unnecessary to me, but I'm not sure of the purpose of their existence:
```shell
bench.js       # 1.5 KB
component.json # 320 B
Makefile       # 115 B
test.js        # 3.16 KB
```
If you count these too, the size from `7.36 KB` becomes `17.4 KB`, and total download-per-week becomes `223.2 MB`.
(here's a similar story of the popular `chokidar` pkg and [how it saved 32 TB of traffic](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/))

One thing about the `test.js` file, is that it effects this "Quality" score that npm calculates:
![Untitled](https://user-images.githubusercontent.com/16363767/131262767-c74be87a-2171-40fb-8b54-08d3a8a23e8b.png)
so if you remove `test.js`, this score will reduce too.
(my personal opinion is that I do not care about that score, and I prefer a tidy published package)

About `component.json`, I don't know whether this is necessary  or not, or is it just kept for backward compatibility reasons,
but I'd very much like to get rid of this as well, since it's been deprecated very long ago.

**Comment by behrang** [comment]
Ok, these files are removed in `1.2.3`, which is published now.
