### ISSUE TITLE
Intl.DateTimeFormat is not accurate for leap years

### ISSUE THREAD

**Issue by Sinakhx** [jalaali/jalaali-js#36]
The docs are now recommending the `Intl.DateTimeFormat` approach for simple conversions.
I just wanted to mention that approach might be troublesome in [some senarios](https://github.com/date-fns-jalali/date-fns-jalali/issues/62).

So, it might be a better idea to rollback the docs to use the library's implementation instead of the built-in `Intl` API.

**Comment by Sinakhx** [comment]
I was actually wrong.
more info: https://github.com/unicode-org/icu/pull/2077#issuecomment-1127190385

**Comment by behrang** [comment]
Thanks for the pull request anyway.

I read the link. How's Jalaali's results compared to ICU? What is the first year in the future that the results diverge? How should we change the docs to reflect this?

**Comment by Sinakhx** [comment]
> I read the link. How's Jalaali's results compared to ICU? What is the first year in the future that the results diverge? How should we change the docs to reflect this?

The first year which diverges from `Intl` results is 1634 AP (233 years from now). I hope the jalaali leap-years calculation dilemma happens to be resolved in the next 2 centuries. 
One can see a comparison [here](https://runkit.com/sinakhx/625929b1a90c8d0007b539a3).

**Comment by behrang** [comment]
Looks like we have enough time. Anyway thanks for the comparison. It would be very helpful to anyone using the project to be aware of this, so I wanted to ask you to add a note and a link to your comparison below the note on Readme.

**Comment by Sinakhx** [comment]
My pleasure. Thanks for your invitation.
