### ISSUE TITLE
Failed to minify 

### ISSUE THREAD

**Issue by mrjavadseydi** [jalaali/jalaali-js#37]
hi 

i'm trying  to run `npm run build` but it's failed to minify on  jalaali-js/index.js:301

the error i get 👇

`Failed to minify the code from this file: ./node_modules/jalaali-js/index.js:301`

i'm using npm version 8.5.0 and node version 16.14.1

**Comment by hosseinizadeh** [comment]
Hi
I have this problem too.
in version 1.2.3 everything is ok but in 1.2.4 not

**Comment by behrang** [comment]
I've updated that line. Might be because of `const` and `let`. Please check again with version 1.2.6 and share the result.

**Comment by mrjavadseydi** [comment]
Thanks for your help .
i've install it again and it's work fine.
