### ISSUE TITLE
this library and others return wrong result?

### ISSUE THREAD

**Issue by shokri-navid** [jalaali/jalaali-js#4]
i use attached codes for converting gregorian date to jalali but in both of them i get wrong result.
this is my test case : 
`<script src="date_convertor.js"></script>
<script>
var date = new Date(1464758201 * 1000);
var pDate = toJalaali(date.getFullYear(), date.getMonth(), date.getDay());
console.log(pDate); 
</script>`

but i am getting 
Object {jy: 1395, jm: 2, jd: 14}
instead of :
Object {jy: 1395, jm: 3, jd: 12}

**Comment by behrang** [comment]
Month in this library is 1-based. Month in JS Date is 0-based. Add 1 to date.getMonth().

**Comment by ehsabd** [comment]
Also getDay() returns the day of the week Navid!. You should use getDate() method. It would be a good idea to make functions work with Date objects.

**Comment by behrang** [comment]
Good idea. Added to `1.1.0`.
