### ISSUE TITLE
Mistake in converting the Gregorian date to Jalali

### ISSUE THREAD

**Issue by SajadFahimian** [jalaali/jalaali-js#44]
hi
I am using this CDN
<script src="https://unpkg.com/jalaali-js/dist/jalaali.min.js"></script>

in my program
![is](https://user-images.githubusercontent.com/57319471/210740077-399d432e-a805-4b06-ac25-67f895bc8e1c.PNG)
but in Jalali calendar **2023/1/5** is **1401/10/15**

**Comment by behrang** [comment]
Date object wants months to be zero-based. So effectively you are converting 2023-02-05 to Jalaali which is 1401-11-16.
