### ISSUE TITLE
NaN Result

### ISSUE THREAD

**Issue by PouriaParhami** [jalaali/jalaali-js#5]
سلام من از این لینک اشتفاده کردم که کد های شما درون اون قرار داره 
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/tree/master/MD.BootstrapPersianDateTimePicker/Scripts
تاریخ به صورت رشته از کار بر گرفته می شه و برای اینکه من رشته را به عدد تبدیل کنم و به فانکشن توگرگورین بدم این کد نوشتم 
 var jj = document.getElementById("fromDate1"),
            bb = document.getElementById("showMe"),
            splitOb, yy, mm, dd, myJson;

```
bb.onclick = function () {
    splitOb = jj.value.split("/");
    for (var i = 0; i < splitOb.length; i++) {
        yy = splitOb[0];
        mm = splitOb[1];
        dd = splitOb[2];
    }

    var xx = yy.trim().toString(), nn = mm.trim().toString(), mmm = dd.trim().toString();

    var xxx = parseInt(xx, 10);
    var nnn = parseInt(nn, 10);
    var mjj = parseInt(mmm, 10);
    var hello = toGregorian(xxx, nnn, mjj);
    alert(hello.gy + "/" + hello.gm + "/" + hello.gd);

    /* var gh= "1395";
     var ghh = parseInt(gh);
     alert(ghh);*/
};
```

امامتغییر های من که از رشته به عدد تبدیل مشن مقدارشون نن میشه ، و خوب فانکشن تاریخ صحیح بر نمی گردونه من هادر کد تاریخ ها را به متغییر ها دادم و کانورت دوباره انجام دادم و درست بود ، این کد
 bb.onclick = function () {

```
    var jjj = "1395";
    var yyyt = "05";
    var kik = "04";

    var xxx = parseInt(jjj, 10);
    var nnn = parseInt(yyyt, 10);
    var mjj = parseInt(kik, 10);

    var hello = toGregorian(xxx, nnn, mjj);
    alert(hello.gy + "/" + hello.gm + "/" + hello.gd);
```

این در ست عمل می کنه ، اما چرا کد اولی که زدم نن بر می گردونه

**Comment by behrang** [comment]
I don't understand this issue. Explain in Persian.

Call `toGregorian` with simple numbers and check the result. If it is not responding with expected values, open an issue, otherwise you have a problem in your number conversion.

**Comment by PouriaParhami** [comment]
ادیت شد 
بله فانکشن ایرادی نداره ، اما متوجه نمی شم چرا متغییر هایی که به صورت هارد کد دیتا گرفتن درست عمل می کنن اما متغییر هایی که به صورت اول نوشته شده  مقدار برگشتی نن مشه ، از دوست عزیزی که لینک شو قرار دادم پرسیدم و ایشون جوابی نداشتن ، در استک اور فلو هم سوال کردم هنوز جوابی نگرفتم

**Comment by behrang** [comment]
آیا در ورودی رقم های فارسی یا عربی نوشتید؟

**Comment by PouriaParhami** [comment]
به صورت فارسی هستند 
مشکل هیمن بود
ممنونم جناب بهرنگ ، شاد سلامت باشید و زندگیتون پر برکت

**Comment by behrang** [comment]
بگردید کتابخانه تبدیل رقم های فارسی پیدا کنید.
