### ISSUE TITLE
Support timestamp

### ISSUE THREAD

**Issue by j209** [jalaali/jalaali-js#7]
Hi
please implement timestamp date format  conversion to jalali and jalali to timestamp

**Comment by behrang** [comment]
Hello,

What do you mean by timestamp? An example would help.

**Comment by alitaheri** [comment]
You can always convert to Gregorian, create a `Date` object from it and convert to number. it will give you the timestamp you need.

See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf) for more info

**Comment by uxitten** [comment]
you can use `jalaali.d2j(new Date(timestamp))`

**Comment by behnammodi** [comment]
you can use `jalaali.toJalaali(new Date(timestamp))`
